export { Desktop } from "./components/Desktop"
export { Window } from "./components/Window"
export { Dock } from "./components/Dock"
export { default as ScrollWatermark } from "./components/ScrollWatermark"
export { useDesktopStore } from "./store"
export type { WindowApp, DesktopState } from "./types"
